
info:
  app:
    name: "@project.artifactId@"
    version: "@project.version@"
management:
  security:
    roles: MANAGE
  context-path: /actuator
server:
  port: 7577
spring:
  main:
    banner-mode: "off"
  data:
    rest:
      base-path: /api
  jpa:
    generate-ddl: true
    properties:
      hibernate.id.new_generator_mappings: true
  cloud:
    skipper:
      server:
        version-info:
          dependency-fetch:
            enabled: false
          dependencies:
            spring-cloud-skipper-server:
              name: Spring Cloud Skipper Server
              version: "@project.version@"
            spring-cloud-skipper-shell:
              name: Spring Cloud Skipper Shell
              version: "@project.version@"
              url: "{repository}/org/springframework/cloud/spring-cloud-skipper-shell/{version}/spring-cloud-skipper-shell-{version}.jar"
              checksum-sha1-url: "{repository}/org/springframework/cloud/spring-cloud-skipper-shell/{version}/spring-cloud-skipper-shell-{version}.jar.sha1"
              checksum-sha256-url: "{repository}/org/springframework/cloud/spring-cloud-skipper-shell/{version}/spring-cloud-skipper-shell-{version}.jar.sha256"
        packageRepositories:
          -
            name: experimental
            url: http://skipper-repository.cfapps.io/repository/experimental
            description: Experimental Skipper Repository
            repoOrder: 0
          -
            name: local
            url: http://${spring.cloud.client.hostname}:7577
            local: true
            description: Default local database backed repository
            repoOrder: 1
      security:
        authorization:
          enabled: true
          permit-all-paths: "/authenticate,/security/info,/features,/assets/**,/dashboard/logout-success-oauth.html"
          authenticated-paths: "/api/**,/,/api"
          rules:
            # About

            - GET    /api/about                      => hasRole('ROLE_VIEW')

             # AppDeployerDatas

            - GET    /api/appDeployerDatas           => hasRole('ROLE_VIEW')

            # Delete

            - DELETE /api/delete/**                  => hasRole('ROLE_CREATE')

            # Deployers

            - GET /api/deployers                     => hasRole('ROLE_VIEW')

            # History

            - GET /api/history/**                    => hasRole('ROLE_VIEW')

            # Install

            - POST /api/install                      => hasRole('ROLE_CREATE')
            - POST /api/install/**                   => hasRole('ROLE_CREATE')

            # List

            - GET /api/list                         => hasRole('ROLE_VIEW')
            - GET /api/list/**                      => hasRole('ROLE_VIEW')

            # Manifest

            - GET /api/manifest/**                  => hasRole('ROLE_VIEW')

            # PackageMetaData

            - GET /api/packageMetadata              => hasRole('ROLE_VIEW')
            - GET /api/packageMetadata/**           => hasRole('ROLE_VIEW')

            # Release

            - GET /api/releases                     => hasRole('ROLE_VIEW')

            # Repositories

            - GET /api/repositories                 => hasRole('ROLE_VIEW')
            - GET /api/repositories/**              => hasRole('ROLE_VIEW')

            # Rollback

            - POST /api/rollback/**                 => hasRole('ROLE_CREATE')

            # Status

            - POST /api/status/**                   => hasRole('ROLE_VIEW')

            # Upgrade

            - POST /api/upgrade                     => hasRole('ROLE_CREATE')

            # Upload

            - POST /api/upload                      => hasRole('ROLE_CREATE')

            # Boot Endpoints

            - GET  /actuator/**                     => hasRole('ROLE_MANAGE')

  mustache:
    check-template-location: false

maven:
  remoteRepositories:
    springRepo:
      url: https://repo.spring.io/libs-snapshot

logging:
  level:
    org.springframework.beans: 'WARN'
    org.springframework.context: 'WARN'
    org.springframework.core.io: 'WARN'
    org.springframework.data: 'WARN'
    org.springframework.jmx: 'WARN'
    org.springframework.web: 'WARN'
    org.springframework.security: 'WARN'
    org.springframework.integration: 'WARN'
    org.springframework.boot: 'WARN'
    org.springframework.boot.context.embedded.tomcat: 'INFO'
    org.hibernate: 'WARN'
    # The following INFO is to log the generated password when using basic security
    org.springframework.boot.autoconfigure.security: 'INFO'
    org.springframework.cloud.skipper: 'INFO'
    org.springframework.statemachine: 'INFO'    
