info:
  app:
    name: "@project.artifactId@"
    version: "@project.version@"
server:
  port: 7577
spring:
  main:
    banner-mode: "off"
  cloud:
    skipper:
      server:
        package-repositories:
          -
            name: test
            url: "file:////Users/igopinatha/workspace/git/spring-cloud/spring-cloud-skipper/spring-cloud-skipper-server/src/test/resources/repositories/binaries/test"

# TODO - remove, pre M1 development simplicity
maven:
  remoteRepositories:
    springRepo:
      url: https://repo.spring.io/libs-snapshot

logging:
  level:
    org.springframework.beans: 'WARN'
    org.springframework.context: 'WARN'
    org.springframework.core.io: 'WARN'
    org.springframework.data: 'WARN'
    org.springframework.jmx: 'WARN'
    org.springframework.web: 'WARN'
    org.springframework.security: 'WARN'
    org.springframework.integration: 'WARN'
    org.springframework.boot: 'WARN'
    org.hibernate: 'WARN'
    # The following INFO is to log the generated password when using basic security
    org.springframework.boot.autoconfigure.security: 'INFO'
    org.springframework.skipper: 'INFO'