apiVersion: skipperPackageMetadata/v1
kind: SpringCloudDeployerApplication
metadata:
  {{#metadata.entrySet}}
  {{key}}: {{value}}
  {{/metadata.entrySet}}
spec:
  resource: {{spec.resource}}
  version: {{version}}
  applicationProperties:
    {{#spec.applicationProperties.entrySet}}
    {{key}}: {{value}}
    {{/spec.applicationProperties.entrySet}}
  deploymentProperties:
    {{#spec.deploymentProperties.entrySet}}
    {{key}}: {{value}}
    {{/spec.deploymentProperties.entrySet}}