name: CI PRs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # cache maven repo
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    # jdk8
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # maven version
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    # build
    - name: Build
      env:
        VERBOSE: ${{ github.debug && 'true' || '' }}
      run: |
        MVN_OPT=
        if [ "$VERBOSE" = "true" ]; then
          MVN_OPT="-X"
        fi
        set +e 
        mvn $MVN_OPT -U -B -s .github/settings.xml dependency:resolve
        set -e
        mvn $MVN_OPT -B -s .github/settings.xml clean package
    # clean m2 cache
    - name: Clean cache
      run: |
        find ~/.m2/repository -type d -name '*SNAPSHOT' | xargs rm -fr
